export const editorTheme = {
  background: '#f3efe6',
  plane: '#e8e0d2',
  gridMinor: '#d7cfbf',
  gridMajor: '#bfb39e',
  surface: 'rgba(255, 251, 245, 0.84)',
  surfaceStrong: 'rgba(250, 244, 235, 0.94)',
  field: 'rgba(255, 251, 245, 0.72)',
  fieldBorder: 'rgba(104, 84, 63, 0.16)',
  text: '#2f2418',
  textMuted: '#6f6253',
  accent: '#4e7a74',
  accentStrong: '#2f6f73',
  accentSoft: 'rgba(196, 138, 58, 0.18)',
  draft: '#4e7a74',
  axisGuide: '#6e8d86',
  snap: '#2f6f73',
  closure: '#b45a3c',
  border: 'rgba(104, 84, 63, 0.12)',
  crosshair: 'rgba(47, 36, 24, 0.52)',
  overlayScrim: 'rgba(243, 239, 230, 0.72)',
  danger: '#b35c4b',
  dangerSoft: 'rgba(179, 92, 75, 0.12)',
} as const;

export const editorThemeVars = {
  background: 'var(--editor-bg)',
  plane: 'var(--editor-plane)',
  gridMinor: 'var(--editor-grid-minor)',
  gridMajor: 'var(--editor-grid-major)',
  surface: 'var(--editor-surface)',
  surfaceStrong: 'var(--editor-surface-strong)',
  field: 'var(--editor-field)',
  fieldBorder: 'var(--editor-field-border)',
  text: 'var(--editor-text)',
  textMuted: 'var(--editor-text-muted)',
  accent: 'var(--editor-accent)',
  accentStrong: 'var(--editor-accent-strong)',
  accentSoft: 'var(--editor-accent-soft)',
  draft: 'var(--editor-draft)',
  axisGuide: 'var(--editor-axis-guide)',
  snap: 'var(--editor-snap)',
  closure: 'var(--editor-closure)',
  border: 'var(--editor-border)',
  crosshair: 'var(--editor-crosshair)',
  overlayScrim: 'var(--editor-overlay-scrim)',
  danger: 'var(--editor-danger)',
  dangerSoft: 'var(--editor-danger-soft)',
} as const;
