export const landingTheme = {
  surface: '#f7f9fb',
  onSurface: '#191c1e',
  onSurfaceVariant: '#544434',
  primaryContainer: '#ff9f1c',
  onPrimaryContainer: '#683c00',
  secondaryFixedDim: '#26dcd6',
  secondaryContainer: '#52f6ef',
  onSecondaryContainer: '#006f6b',
  secondary: '#006a66',
  surfaceContainerLow: '#f2f4f6',
  surfaceContainerHigh: '#e6e8ea',
  outlineVariant: '#dac2ae',
  fontHeadline: '"Space Grotesk", sans-serif',
  fontBody: '"Manrope", sans-serif',
  fontLabel: '"Manrope", sans-serif',
} as const;
