-- 001-init.sql  —  Asset library schema (idempotent)
-- Run: psql $DATABASE_URL -f server/migrations/001-init.sql

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ──────────────────────────────────────────────
-- Categories
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS categories (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  slug VARCHAR(50) NOT NULL,
  CONSTRAINT categories_slug_format CHECK (slug ~ '^[a-z0-9-]+$')
);

CREATE UNIQUE INDEX IF NOT EXISTS categories_slug_unique_lower ON categories (lower(slug));

INSERT INTO categories (name, slug) VALUES
  ('沙发', 'sofa'), ('桌子', 'table'), ('椅子', 'chair'),
  ('床', 'bed'), ('灯具', 'light'), ('柜子', 'cabinet'),
  ('装饰', 'decoration'), ('其他', 'other')
ON CONFLICT DO NOTHING;

-- ──────────────────────────────────────────────
-- Assets
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS assets (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name         VARCHAR(200) NOT NULL,
  category_id  INT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
  file_path    VARCHAR(500) NOT NULL UNIQUE,
  thumb_path   VARCHAR(500),
  file_size    BIGINT NOT NULL CHECK (file_size > 0),
  bbox_min_x   DOUBLE PRECISION NOT NULL,
  bbox_min_y   DOUBLE PRECISION NOT NULL,
  bbox_min_z   DOUBLE PRECISION NOT NULL,
  bbox_size_x  DOUBLE PRECISION NOT NULL CHECK (bbox_size_x > 0),
  bbox_size_y  DOUBLE PRECISION NOT NULL CHECK (bbox_size_y > 0),
  bbox_size_z  DOUBLE PRECISION NOT NULL CHECK (bbox_size_z > 0),
  auto_scale   DOUBLE PRECISION NOT NULL DEFAULT 1 CHECK (auto_scale > 0),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_assets_category ON assets(category_id);

-- ──────────────────────────────────────────────
-- updated_at trigger
-- ──────────────────────────────────────────────
CREATE OR REPLACE FUNCTION assets_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 使用 DO block 来幂等创建 trigger
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_assets_updated_at'
  ) THEN
    CREATE TRIGGER trg_assets_updated_at
      BEFORE UPDATE ON assets
      FOR EACH ROW EXECUTE FUNCTION assets_set_updated_at();
  END IF;
END $$;
